language: java
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: www.aerialmarks.com
    endpoint: www.aerialmarks.com.s3-website-us-east-1.amazonaws.com
    region: us-east-1
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
